### ISSUE TITLE
Emails not working

### ISSUE THREAD

**Issue by afgallo** [JKHeadley/appy-backend#1]
Hi @JKHeadley, thanks for this boilerplate. It has come in pretty handy!

I realised when testing that emails weren't working due to a wrong folder path you had in **server/mailer.js**. I made the change bellow and it worked!

![image](https://cloud.githubusercontent.com/assets/9999415/22856253/225ece9e-f075-11e6-96f3-14801a725250.png)

Let me know if you would like a PR for this.

Cheers!

**Comment by JKHeadley** [comment]
Hey @afgallo, glad you like it! That's a great catch. I recently changed the folder structure up a bit so I'll try to go through and make sure all the paths are correct.  Ideally I would have tests checking all this but I've been pushed for time and just wanted to get the project out to get some feedback.

If you don't mind, I would appreciate a PR just so I can make sure the PR flow is smooth.  Thanks!

**Comment by afgallo** [comment]
OK done with the PR #2. I request the merge to master as there was no develop branch as per your contributing guide. Hope it works!
