### ISSUE TITLE
Do we need PasswordHash in Refresh Token?

### ISSUE THREAD

**Issue by rahil471** [JKHeadley/appy-backend#11]
Hi @JKHeadley 

I've observed that `passwordHash`  is sent in RefreshToken. May be I'm missing something, could you point me the reason for having it over there?

**Comment by JKHeadley** [comment]
It's basically an added security feature.  If the user changes their password then any existing tokens get invalidated.  

https://github.com/JKHeadley/appy/blob/ef6f209368ea63600243a84c61ce1abc7b8eaa02/server/auth.js#L159

This is mostly useful if you allow multiple user sessions (i.e. a user can login to multiple devices at the same time).  With the current appy configuration, when a user logs into one device, the previous session is destroyed, effectively logging the user out of all other devices.  I will probably update appy in the future to support multiple sessions.  In that case if a user ever felt that their account had been compromised (i.e. a hacker stole a refresh token or password), then they could easily invalidate all their current tokens by changing their password.

You can see some discussion about this at this SO post (mostly the second answer):

https://stackoverflow.com/questions/28759590/best-practices-to-invalidate-jwt-while-changing-passwords-and-logout-in-node-js
