### ISSUE TITLE
hoek dependency interrupts gulp

### ISSUE THREAD

**Issue by cloopadoop** [JKHeadley/appy-backend#21]
> appy\node_modules\hapi-auth-jwt2\node_modules\boom\node_modules\hoek\lib\index.js:719
> exports.assert = function (condition, ...args){
> 
> SyntaxError: Unexpected token ...

I guess this is technically a hoek issue. Is there a specific version you typically run that I should install?

**Comment by JKHeadley** [comment]
It might be your version of hapi-auth-jwt2, do you have 7.2.4?

Just fyi, I don't have "hoek" as a direct dependency, but my current version is at 4.1.0

**Comment by cloopadoop** [comment]
npm install hapi-auth-jwt2@7.2.4 seems to have done the trick. Thanks! :)

**Comment by JKHeadley** [comment]
Just FYI this was likely due to hapi-auth-jwt upgrading to Hapi 17. Hopefully appy can make the same upgrade in the near future.
