### ISSUE TITLE
Adding a front end

### ISSUE THREAD

**Issue by andersea** [JKHeadley/appy-backend#3]
Hi. Would it be possible to add a wiki page or some pointers in the readme on some ideas about how to add a front end. I am a bit overwhelmed with all the different files.

I am guessing it has something to do with adding a front end file to server folder and making some adjustments to the manifest.js?

**Comment by JKHeadley** [comment]
Hi @andersea, there are many options/routes to adding a front end, however ideally a front end project would be completely separate from the appy server.  For example, you might write an angular app in a separate project.  appy simply provides an api that the front end would communicate with for services such as logging in, authenticating requests, and accessing data.

I'm currently working on a front-end portion for appy. I'm not sure when it will be complete but I'm expecting it will make it much more clear how the appy system should function as a whole.

**Comment by andersea** [comment]
Very useful advice. Thanks!
