### ISSUE TITLE
implement dynamic scopes allowing access to specific documents

### ISSUE THREAD

**Issue by JKHeadley** [JKHeadley/appy-backend#6]

**Comment by ghost** [comment]
Please +1 :) .  This is a huge use case for us Hapi learners!  Thank you so much for this repo.

**Comment by JKHeadley** [comment]
This feature was added in JKHeadley/rest-hapi#65.  Please see the [changelog](https://github.com/JKHeadley/rest-hapi/blob/master/CHANGELOG.md) (v0.29.0) for links to new feature documentation.
