### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by thiagoananias** [JKHeadley/appy-backend#7]
Hello, i have a begginers question: How may i debug the code, for example, i'am using Visual Studio Code and have the following configuration file

> {
>     "version": "0.2.0",
>     "configurations": [
>         {
>             "type": "node",
>             "request": "launch",
>             "name": "Gulp task",
>             "program": "${workspaceRoot}/node_modules/gulp/bin/gulp.js",
>             "args": [
>                 "serve:development", "--colors"
>             ]
>         }
>     ]
> }

with this i can see that for example, the Gulp code inside node_modules is debuggable cause the breakpoint stops there, but the code server.js and server/register are not stoping...

And inside the server/models/my.model.js i have a create:pre function defined, the function is executed as well but the debug is not being fired

Thanks!

**Comment by JKHeadley** [comment]
Hi @thiagoananias, thanks for your interest. Unfortunately I'm not very familiar with VS Code and its debugging features.  I personally use Webstorm for node.js development, and I'm pretty sure it allows for breakpoints to be set for any code that is executed. I highly recommend it.

**Comment by thiagoananias** [comment]
Thank you
